# Generated by Django 4.1.7 on 2023-04-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crudcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.BigIntegerField(default=0)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
