# Generated by Django 4.1.7 on 2023-06-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_registration_alter_crudcard_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crudcard',
        ),
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='roll',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
