# Generated by Django 4.1.7 on 2023-06-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0004_crudcard_remove_registration_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crudcard',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
