# Generated by Django 4.1.7 on 2023-06-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0008_alter_crudcard_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crudcard',
        ),
    ]
