# Generated by Django 4.1.7 on 2023-06-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0011_alter_crudcard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
    ]
