# Generated by Django 4.1.7 on 2023-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0012_remove_registration_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
