# Generated by Django 4.1.7 on 2023-06-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0015_alter_registration_up_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
