# Generated by Django 4.1.7 on 2023-06-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0018_registration_user_alter_registration_up_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
    ]
